# Generated by Django 6.0.1 on 2026-01-30 19:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # ========================================
        # CRIA O SCHEMA ANTES DE TUDO
        # ========================================
        migrations.RunSQL(
            sql='CREATE SCHEMA IF NOT EXISTS carga_org_lot;',
            reverse_sql='DROP SCHEMA IF EXISTS carga_org_lot CASCADE;'
        ),
        # ========================================
        # FIM DA CRIAÇÃO DO SCHEMA
        # ========================================
                
        migrations.CreateModel(
            name='TblLotacaoVersao',
            fields=[
                ('id_lotacao_versao', models.BigAutoField(db_column='idlotacaoversao', primary_key=True, serialize=False)),
                ('str_origem', models.CharField(db_column='strorigem', max_length=50)),
                ('str_tipo_arquivo_original', models.CharField(blank=True, db_column='strtipoarquivooriginal', max_length=20, null=True)),
                ('str_nome_arquivo_original', models.CharField(blank=True, db_column='strnomearquivooriginal', max_length=255, null=True)),
                ('dat_processamento', models.DateTimeField(db_column='datprocessamento', default=django.utils.timezone.now)),
                ('str_status_processamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], db_column='strstatusprocessamento', default='PENDENTE', max_length=30)),
                ('str_mensagem_processamento', models.TextField(blank=True, db_column='strmensagemprocessamento', null=True)),
                ('flg_ativo', models.BooleanField(db_column='flgativo', default=False)),
            ],
            options={
                'verbose_name': 'Versão de Lotação',
                'verbose_name_plural': 'Versões de Lotação',
                'db_table': '"carga_org_lot"."tbllotacaoversao"',
                'ordering': ['-id_lotacao_versao'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblOrganogramaVersao',
            fields=[
                ('id_organograma_versao', models.BigAutoField(db_column='idorganogramaversao', primary_key=True, serialize=False)),
                ('str_origem', models.CharField(db_column='strorigem', help_text='Origem dos dados (API, UPLOAD, MANUAL)', max_length=50)),
                ('str_tipo_arquivo_original', models.CharField(blank=True, db_column='strtipoarquivooriginal', max_length=20, null=True)),
                ('str_nome_arquivo_original', models.CharField(blank=True, db_column='strnomearquivooriginal', max_length=255, null=True)),
                ('dat_processamento', models.DateTimeField(db_column='datprocessamento', default=django.utils.timezone.now)),
                ('str_status_processamento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('SUCESSO', 'Sucesso'), ('ERRO', 'Erro'), ('CANCELADO', 'Cancelado')], db_column='strstatusprocessamento', default='PENDENTE', max_length=30)),
                ('str_mensagem_processamento', models.TextField(blank=True, db_column='strmensagemprocessamento', null=True)),
                ('flg_ativo', models.BooleanField(db_column='flgativo', default=False, help_text='Indica se esta é a versão ativa')),
            ],
            options={
                'verbose_name': 'Versão de Organograma',
                'verbose_name_plural': 'Versões de Organograma',
                'db_table': '"carga_org_lot"."tblorganogramaversao"',
                'ordering': ['-id_organograma_versao'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblStatusCarga',
            fields=[
                ('id_status_carga', models.SmallIntegerField(db_column='idstatuscarga', primary_key=True, serialize=False)),
                ('str_descricao', models.CharField(db_column='strdescricao', max_length=150)),
                ('flg_sucesso', models.IntegerField(db_column='flgsucesso')),
            ],
            options={
                'verbose_name': 'Status Carga',
                'verbose_name_plural': 'Status Carga',
                'db_table': '"carga_org_lot"."tblstatuscarga"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblStatusProgresso',
            fields=[
                ('id_status_progresso', models.SmallIntegerField(db_column='idstatusprogresso', primary_key=True, serialize=False)),
                ('str_descricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'verbose_name': 'Status Progresso',
                'verbose_name_plural': 'Status Progresso',
                'db_table': '"carga_org_lot"."tblstatusprogresso"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblStatusTokenEnvioCarga',
            fields=[
                ('id_status_token_envio_carga', models.SmallIntegerField(db_column='idstatustokenenviocarga', primary_key=True, serialize=False)),
                ('str_descricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'verbose_name': 'Status Token Envio Carga',
                'verbose_name_plural': 'Status Token Envio Carga',
                'db_table': '"carga_org_lot"."tblstatustokenenviocarga"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblTipoCarga',
            fields=[
                ('id_tipo_carga', models.SmallIntegerField(db_column='idtipocarga', primary_key=True, serialize=False)),
                ('str_descricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Carga',
                'verbose_name_plural': 'Tipos Carga',
                'db_table': '"carga_org_lot"."tbltipocarga"',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblLotacao',
            fields=[
                ('id_lotacao', models.BigAutoField(db_column='idlotacao', primary_key=True, serialize=False)),
                ('str_cpf', models.CharField(db_column='strcpf', help_text='CPF do servidor', max_length=14)),
                ('str_cargo_original', models.CharField(blank=True, db_column='strcargooriginal', max_length=255, null=True)),
                ('str_cargo_normalizado', models.CharField(blank=True, db_column='strcargonormalizado', max_length=255, null=True)),
                ('flg_valido', models.BooleanField(db_column='flgvalido', default=True)),
                ('str_erros_validacao', models.TextField(blank=True, db_column='strerrosvalidacao', null=True)),
                ('dat_referencia', models.DateField(blank=True, db_column='datreferencia', null=True)),
                ('dat_criacao', models.DateTimeField(db_column='datcriacao', default=django.utils.timezone.now)),
                ('dat_alteracao', models.DateTimeField(blank=True, db_column='datalteracao', null=True)),
                ('id_usuario_alteracao', models.ForeignKey(blank=True, db_column='idusuarioalteracao', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes_alteradas', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_criacao', models.ForeignKey(blank=True, db_column='idusuariocriacao', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('id_lotacao_versao', models.ForeignKey(db_column='idlotacaoversao', on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes', to='carga_org_lot.tbllotacaoversao')),
                ('id_organograma_versao', models.ForeignKey(db_column='idorganogramaversao', on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes', to='carga_org_lot.tblorganogramaversao')),
            ],
            options={
                'verbose_name': 'Lotação',
                'verbose_name_plural': 'Lotações',
                'db_table': '"carga_org_lot"."tbllotacao"',
                'ordering': ['str_cpf'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblLotacaoInconsistencia',
            fields=[
                ('id_inconsistencia', models.BigAutoField(db_column='idinconsistencia', primary_key=True, serialize=False)),
                ('str_tipo', models.CharField(db_column='strtipo', max_length=100)),
                ('str_detalhe', models.TextField(db_column='strdetalhe')),
                ('dat_registro', models.DateTimeField(db_column='datregistro', default=django.utils.timezone.now)),
                ('id_lotacao', models.ForeignKey(db_column='idlotacao', on_delete=django.db.models.deletion.CASCADE, related_name='inconsistencias', to='carga_org_lot.tbllotacao')),
            ],
            options={
                'verbose_name': 'Inconsistência de Lotação',
                'verbose_name_plural': 'Inconsistências de Lotação',
                'db_table': '"carga_org_lot"."tbllotacaoinconsistencia"',
                'ordering': ['-dat_registro'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblOrganogramaJson',
            fields=[
                ('id_organograma_json', models.BigAutoField(db_column='idorganogramajson', primary_key=True, serialize=False)),
                ('js_conteudo', models.JSONField(db_column='jsconteudo')),
                ('dat_criacao', models.DateTimeField(db_column='datcriacao', default=django.utils.timezone.now)),
                ('dat_envio_api', models.DateTimeField(blank=True, db_column='datenvioapi', null=True)),
                ('str_status_envio', models.CharField(blank=True, db_column='strstatusenvio', max_length=30, null=True)),
                ('str_mensagem_retorno', models.TextField(blank=True, db_column='strmensagemretorno', null=True)),
                ('id_organograma_versao', models.OneToOneField(db_column='idorganogramaversao', on_delete=django.db.models.deletion.CASCADE, related_name='json_organograma', to='carga_org_lot.tblorganogramaversao')),
            ],
            options={
                'verbose_name': 'JSON Organograma',
                'verbose_name_plural': 'JSONs Organograma',
                'db_table': '"carga_org_lot"."tblorganogramajson"',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tbllotacaoversao',
            name='id_organograma_versao',
            field=models.ForeignKey(db_column='idorganogramaversao', on_delete=django.db.models.deletion.CASCADE, related_name='versoes_lotacao', to='carga_org_lot.tblorganogramaversao'),
        ),
        migrations.CreateModel(
            name='TblOrgaoUnidade',
            fields=[
                ('id_orgao_unidade', models.BigAutoField(db_column='idorgaounidade', primary_key=True, serialize=False)),
                ('str_nome', models.CharField(db_column='strnome', help_text='Nome completo do órgão/unidade', max_length=255)),
                ('str_sigla', models.CharField(db_column='strsigla', help_text='Sigla do órgão/unidade', max_length=50)),
                ('str_numero_hierarquia', models.CharField(blank=True, db_column='strnumerohierarquia', help_text='Número hierárquico (ex: 1.2.3)', max_length=50, null=True)),
                ('int_nivel_hierarquia', models.IntegerField(blank=True, db_column='intnivelhierarquia', help_text='Nível na hierarquia (0 = raiz)', null=True)),
                ('flg_ativo', models.BooleanField(db_column='flgativo', default=True)),
                ('dat_criacao', models.DateTimeField(db_column='datcriacao', default=django.utils.timezone.now)),
                ('dat_alteracao', models.DateTimeField(blank=True, db_column='datalteracao', null=True)),
                ('id_organograma_versao', models.ForeignKey(db_column='idorganogramaversao', on_delete=django.db.models.deletion.RESTRICT, related_name='orgaos_unidades', to='carga_org_lot.tblorganogramaversao')),
                ('id_orgao_unidade_pai', models.ForeignKey(blank=True, db_column='idorgaounidadepai', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_filhas', to='carga_org_lot.tblorgaounidade')),
                ('id_usuario_alteracao', models.ForeignKey(blank=True, db_column='idusuarioalteracao', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orgaos_alterados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_criacao', models.ForeignKey(blank=True, db_column='idusuariocriacao', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orgaos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Órgão/Unidade',
                'verbose_name_plural': 'Órgãos/Unidades',
                'db_table': '"carga_org_lot"."tblorgaounidade"',
                'ordering': ['str_numero_hierarquia'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tbllotacao',
            name='id_orgao_lotacao',
            field=models.ForeignKey(db_column='idorgaolotacao', on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes_orgao', to='carga_org_lot.tblorgaounidade'),
        ),
        migrations.AddField(
            model_name='tbllotacao',
            name='id_unidade_lotacao',
            field=models.ForeignKey(blank=True, db_column='idunidadelotacao', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes_unidade', to='carga_org_lot.tblorgaounidade'),
        ),
        migrations.CreateModel(
            name='TblPatriarca',
            fields=[
                ('id_patriarca', models.BigAutoField(db_column='idpatriarca', primary_key=True, serialize=False)),
                ('id_externo_patriarca', models.UUIDField(db_column='idexternopatriarca', default=uuid.uuid4, editable=False, unique=True)),
                ('str_sigla_patriarca', models.CharField(db_column='strsiglapatriarca', help_text='Sigla do patriarca (ex: SEGER, SEDU)', max_length=20)),
                ('str_nome', models.CharField(db_column='strnome', help_text='Nome completo do patriarca', max_length=255)),
                ('dat_criacao', models.DateTimeField(db_column='datcriacao', default=django.utils.timezone.now)),
                ('dat_alteracao', models.DateTimeField(blank=True, db_column='datalteracao', null=True)),
                ('id_usuario_alteracao', models.ForeignKey(blank=True, db_column='idusuarioalteracao', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patriarcas_alterados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_criacao', models.ForeignKey(db_column='idusuariocriacao', on_delete=django.db.models.deletion.PROTECT, related_name='patriarcas_criados', to=settings.AUTH_USER_MODEL)),
                ('id_status_progresso', models.ForeignKey(db_column='idstatusprogresso', on_delete=django.db.models.deletion.PROTECT, related_name='patriarcas', to='carga_org_lot.tblstatusprogresso')),
            ],
            options={
                'verbose_name': 'Patriarca',
                'verbose_name_plural': 'Patriarcas',
                'db_table': '"carga_org_lot"."tblpatriarca"',
                'ordering': ['str_sigla_patriarca'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tblorgaounidade',
            name='id_patriarca',
            field=models.ForeignKey(db_column='idpatriarca', on_delete=django.db.models.deletion.RESTRICT, related_name='orgaos_unidades', to='carga_org_lot.tblpatriarca'),
        ),
        migrations.AddField(
            model_name='tblorganogramaversao',
            name='id_patriarca',
            field=models.ForeignKey(db_column='idpatriarca', on_delete=django.db.models.deletion.CASCADE, related_name='versoes_organograma', to='carga_org_lot.tblpatriarca'),
        ),
        migrations.AddField(
            model_name='tbllotacaoversao',
            name='id_patriarca',
            field=models.ForeignKey(db_column='idpatriarca', on_delete=django.db.models.deletion.CASCADE, related_name='versoes_lotacao', to='carga_org_lot.tblpatriarca'),
        ),
        migrations.CreateModel(
            name='TblLotacaoJsonOrgao',
            fields=[
                ('id_lotacao_json_orgao', models.BigAutoField(db_column='idlotacaojsonorgao', primary_key=True, serialize=False)),
                ('js_conteudo', models.JSONField(db_column='jsconteudo')),
                ('dat_criacao', models.DateTimeField(db_column='datcriacao', default=django.utils.timezone.now)),
                ('dat_envio_api', models.DateTimeField(blank=True, db_column='datenvioapi', null=True)),
                ('str_status_envio', models.CharField(blank=True, db_column='strstatusenvio', max_length=30, null=True)),
                ('str_mensagem_retorno', models.TextField(blank=True, db_column='strmensagemretorno', null=True)),
                ('id_lotacao_versao', models.ForeignKey(db_column='idlotacaoversao', on_delete=django.db.models.deletion.CASCADE, related_name='jsons_orgao', to='carga_org_lot.tbllotacaoversao')),
                ('id_organograma_versao', models.ForeignKey(db_column='idorganogramaversao', on_delete=django.db.models.deletion.CASCADE, related_name='jsons_lotacao', to='carga_org_lot.tblorganogramaversao')),
                ('id_orgao_lotacao', models.ForeignKey(db_column='idorgaolotacao', on_delete=django.db.models.deletion.CASCADE, related_name='jsons_lotacao', to='carga_org_lot.tblorgaounidade')),
                ('id_patriarca', models.ForeignKey(db_column='idpatriarca', on_delete=django.db.models.deletion.CASCADE, related_name='jsons_lotacao', to='carga_org_lot.tblpatriarca')),
            ],
            options={
                'verbose_name': 'JSON Lotação por Órgão',
                'verbose_name_plural': 'JSONs Lotação por Órgão',
                'db_table': '"carga_org_lot"."tbllotacaojsonorgao"',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tbllotacao',
            name='id_patriarca',
            field=models.ForeignKey(db_column='idpatriarca', on_delete=django.db.models.deletion.CASCADE, related_name='lotacoes', to='carga_org_lot.tblpatriarca'),
        ),
        migrations.CreateModel(
            name='TblCargaPatriarca',
            fields=[
                ('id_carga_patriarca', models.BigAutoField(db_column='idcargapatriarca', primary_key=True, serialize=False)),
                ('str_mensagem_retorno', models.TextField(blank=True, db_column='strmensagemretorno', null=True)),
                ('dat_data_hora_inicio', models.DateTimeField(db_column='datdatahorainicio', default=django.utils.timezone.now)),
                ('dat_data_hora_fim', models.DateTimeField(blank=True, db_column='datdatahorafim', null=True)),
                ('id_patriarca', models.ForeignKey(db_column='idpatriarca', on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='carga_org_lot.tblpatriarca')),
                ('id_status_carga', models.ForeignKey(db_column='idstatuscarga', on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='carga_org_lot.tblstatuscarga')),
                ('id_tipo_carga', models.ForeignKey(db_column='idtipocarga', on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='carga_org_lot.tbltipocarga')),
            ],
            options={
                'verbose_name': 'Carga Patriarca',
                'verbose_name_plural': 'Cargas Patriarca',
                'db_table': '"carga_org_lot"."tblcargapatriarca"',
                'ordering': ['-dat_data_hora_inicio'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblDetalheStatusCarga',
            fields=[
                ('id_detalhe_status_carga', models.BigAutoField(db_column='iddetalhestatuscarga', primary_key=True, serialize=False)),
                ('dat_registro', models.DateTimeField(db_column='datregistro', default=django.utils.timezone.now)),
                ('str_mensagem', models.TextField(blank=True, db_column='strmensagem', null=True)),
                ('id_carga_patriarca', models.ForeignKey(db_column='idcargapatriarca', on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_status', to='carga_org_lot.tblcargapatriarca')),
                ('id_status_carga', models.ForeignKey(db_column='idstatuscarga', on_delete=django.db.models.deletion.PROTECT, related_name='detalhes', to='carga_org_lot.tblstatuscarga')),
            ],
            options={
                'verbose_name': 'Detalhe Status Carga',
                'verbose_name_plural': 'Detalhes Status Carga',
                'db_table': '"carga_org_lot"."tbldetalhestatuscarga"',
                'ordering': ['dat_registro'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblTokenEnvioCarga',
            fields=[
                ('id_token_envio_carga', models.BigAutoField(db_column='idtokenenviocarga', primary_key=True, serialize=False)),
                ('str_token_retorno', models.CharField(db_column='strtokenretorno', max_length=1000)),
                ('dat_data_hora_inicio', models.DateTimeField(db_column='datdatahorainicio', default=django.utils.timezone.now)),
                ('dat_data_hora_fim', models.DateTimeField(blank=True, db_column='datdatahorafim', null=True)),
                ('id_patriarca', models.ForeignKey(db_column='idpatriarca', on_delete=django.db.models.deletion.CASCADE, related_name='tokens_envio', to='carga_org_lot.tblpatriarca')),
                ('id_status_token_envio_carga', models.ForeignKey(db_column='idstatustokenenviocarga', on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='carga_org_lot.tblstatustokenenviocarga')),
            ],
            options={
                'verbose_name': 'Token Envio Carga',
                'verbose_name_plural': 'Tokens Envio Carga',
                'db_table': '"carga_org_lot"."tbltokenenviocarga"',
                'ordering': ['-dat_data_hora_inicio'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tblcargapatriarca',
            name='id_token_envio_carga',
            field=models.ForeignKey(db_column='idtokenenviocarga', on_delete=django.db.models.deletion.CASCADE, related_name='cargas', to='carga_org_lot.tbltokenenviocarga'),
        ),
    ]
