# Generated by Django 6.0.1 on 2026-01-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblCargaPatriarca',
            fields=[
                ('id_carga_patriarca', models.BigAutoField(db_column='idcargapatriarca', primary_key=True, serialize=False)),
                ('str_mensagem_retorno', models.TextField(blank=True, db_column='strmensagemretorno', null=True)),
                ('dat_data_hora_inicio', models.DateTimeField(db_column='datdatahorainicio')),
                ('dat_data_hora_fim', models.DateTimeField(blank=True, db_column='datdatahorafim', null=True)),
            ],
            options={
                'verbose_name': 'Carga Patriarca',
                'verbose_name_plural': 'Cargas Patriarca',
                'db_table': 'carga_org_lot.tblcargapatriarca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDetalheStatusCarga',
            fields=[
                ('id_detalhe_status_carga', models.BigAutoField(db_column='iddetalhestatuscarga', primary_key=True, serialize=False)),
                ('dat_registro', models.DateTimeField(db_column='datregistro')),
                ('str_mensagem', models.TextField(blank=True, db_column='strmensagem', null=True)),
            ],
            options={
                'verbose_name': 'Detalhe Status Carga',
                'verbose_name_plural': 'Detalhes Status Carga',
                'db_table': 'carga_org_lot.tbldetalhestatuscarga',
                'ordering': ['dat_registro'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLotacao',
            fields=[
                ('id_lotacao', models.BigAutoField(db_column='idlotacao', primary_key=True, serialize=False)),
                ('str_cpf', models.CharField(db_column='strcpf', max_length=14)),
                ('str_cargo_original', models.CharField(blank=True, db_column='strcargooriginal', max_length=255, null=True)),
                ('str_cargo_normalizado', models.CharField(blank=True, db_column='strcargonormalizado', max_length=255, null=True)),
                ('flg_valido', models.BooleanField(db_column='flgvalido')),
                ('str_erros_validacao', models.TextField(blank=True, db_column='strerrosvalidacao', null=True)),
                ('dat_referencia', models.DateField(blank=True, db_column='datreferencia', null=True)),
                ('dat_criacao', models.DateTimeField(db_column='datcriacao')),
                ('dat_alteracao', models.DateTimeField(blank=True, db_column='datalteracao', null=True)),
            ],
            options={
                'verbose_name': 'Lotação',
                'verbose_name_plural': 'Lotações',
                'db_table': 'carga_org_lot.tbllotacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLotacaoInconsistencia',
            fields=[
                ('id_inconsistencia', models.BigAutoField(db_column='idinconsistencia', primary_key=True, serialize=False)),
                ('str_tipo', models.CharField(db_column='strtipo', max_length=100)),
                ('str_detalhe', models.TextField(db_column='strdetalhe')),
                ('dat_registro', models.DateTimeField(db_column='datregistro')),
            ],
            options={
                'verbose_name': 'Inconsistência de Lotação',
                'verbose_name_plural': 'Inconsistências de Lotação',
                'db_table': 'carga_org_lot.tbllotacaoinconsistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLotacaoJsonOrgao',
            fields=[
                ('id_lotacao_json_orgao', models.BigAutoField(db_column='idlotacaojsonorgao', primary_key=True, serialize=False)),
                ('js_conteudo', models.JSONField(db_column='jsconteudo')),
                ('dat_criacao', models.DateTimeField(db_column='datcriacao')),
                ('dat_envio_api', models.DateTimeField(blank=True, db_column='datenvioapi', null=True)),
                ('str_status_envio', models.CharField(blank=True, db_column='strstatusenvio', max_length=30, null=True)),
                ('str_mensagem_retorno', models.TextField(blank=True, db_column='strmensagemretorno', null=True)),
            ],
            options={
                'verbose_name': 'JSON Lotação por Órgão',
                'verbose_name_plural': 'JSONs Lotação por Órgão',
                'db_table': 'carga_org_lot.tbllotacaojsonorgao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLotacaoVersao',
            fields=[
                ('id_lotacao_versao', models.BigAutoField(db_column='idlotacaoversao', primary_key=True, serialize=False)),
                ('str_origem', models.CharField(db_column='strorigem', max_length=50)),
                ('str_tipo_arquivo_original', models.CharField(blank=True, db_column='strtipoarquivooriginal', max_length=20, null=True)),
                ('str_nome_arquivo_original', models.CharField(blank=True, db_column='strnomearquivooriginal', max_length=255, null=True)),
                ('dat_processamento', models.DateTimeField(db_column='datprocessamento')),
                ('str_status_processamento', models.CharField(db_column='strstatusprocessamento', max_length=30)),
                ('str_mensagem_processamento', models.TextField(blank=True, db_column='strmensagemprocessamento', null=True)),
                ('flg_ativo', models.BooleanField(db_column='flgativo')),
            ],
            options={
                'verbose_name': 'Versão de Lotação',
                'verbose_name_plural': 'Versões de Lotação',
                'db_table': 'carga_org_lot.tbllotacaoversao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOrganogramaJson',
            fields=[
                ('id_organograma_json', models.BigAutoField(db_column='idorganogramajson', primary_key=True, serialize=False)),
                ('js_conteudo', models.JSONField(db_column='jsconteudo')),
                ('dat_criacao', models.DateTimeField(db_column='datcriacao')),
                ('dat_envio_api', models.DateTimeField(blank=True, db_column='datenvioapi', null=True)),
                ('str_status_envio', models.CharField(blank=True, db_column='strstatusenvio', max_length=30, null=True)),
                ('str_mensagem_retorno', models.TextField(blank=True, db_column='strmensagemretorno', null=True)),
            ],
            options={
                'verbose_name': 'JSON Organograma',
                'verbose_name_plural': 'JSONs Organograma',
                'db_table': 'carga_org_lot.tblorganogramajson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOrganogramaVersao',
            fields=[
                ('id_organograma_versao', models.BigAutoField(db_column='idorganogramaversao', primary_key=True, serialize=False)),
                ('str_origem', models.CharField(db_column='strorigem', max_length=50)),
                ('str_tipo_arquivo_original', models.CharField(blank=True, db_column='strtipoarquivooriginal', max_length=20, null=True)),
                ('str_nome_arquivo_original', models.CharField(blank=True, db_column='strnomearquivooriginal', max_length=255, null=True)),
                ('dat_processamento', models.DateTimeField(db_column='datprocessamento')),
                ('str_status_processamento', models.CharField(db_column='strstatusprocessamento', max_length=30)),
                ('str_mensagem_processamento', models.TextField(blank=True, db_column='strmensagemprocessamento', null=True)),
                ('flg_ativo', models.BooleanField(db_column='flgativo')),
            ],
            options={
                'verbose_name': 'Versão de Organograma',
                'verbose_name_plural': 'Versões de Organograma',
                'db_table': 'carga_org_lot.tblorganogramaversao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblOrgaoUnidade',
            fields=[
                ('id_orgao_unidade', models.BigAutoField(db_column='idorgaounidade', primary_key=True, serialize=False)),
                ('str_nome', models.CharField(db_column='strnome', max_length=255)),
                ('str_sigla', models.CharField(db_column='strsigla', max_length=50)),
                ('str_numero_hierarquia', models.CharField(blank=True, db_column='strnumerohierarquia', max_length=50, null=True)),
                ('int_nivel_hierarquia', models.IntegerField(blank=True, db_column='intnivelhierarquia', null=True)),
                ('flg_ativo', models.BooleanField(db_column='flgativo')),
                ('dat_criacao', models.DateTimeField(db_column='datcriacao')),
                ('dat_alteracao', models.DateTimeField(blank=True, db_column='datalteracao', null=True)),
            ],
            options={
                'verbose_name': 'Órgão/Unidade',
                'verbose_name_plural': 'Órgãos/Unidades',
                'db_table': 'carga_org_lot.tblorgaounidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPatriarca',
            fields=[
                ('id_patriarca', models.BigAutoField(db_column='idpatriarca', primary_key=True, serialize=False)),
                ('id_externo_patriarca', models.UUIDField(db_column='idexternopatriarca', unique=True)),
                ('str_sigla_patriarca', models.CharField(db_column='strsiglapatriarca', max_length=20)),
                ('str_nome', models.CharField(db_column='strnome', max_length=255)),
                ('dat_criacao', models.DateTimeField(db_column='datcriacao')),
                ('dat_alteracao', models.DateTimeField(blank=True, db_column='datalteracao', null=True)),
            ],
            options={
                'verbose_name': 'Patriarca',
                'verbose_name_plural': 'Patriarcas',
                'db_table': 'carga_org_lot.tblpatriarca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblStatusCarga',
            fields=[
                ('id_status_carga', models.SmallIntegerField(db_column='idstatuscarga', primary_key=True, serialize=False)),
                ('str_descricao', models.CharField(db_column='strdescricao', max_length=150)),
                ('flg_sucesso', models.IntegerField(db_column='flgsucesso')),
            ],
            options={
                'verbose_name': 'Status Carga',
                'verbose_name_plural': 'Status Carga',
                'db_table': 'carga_org_lot.tblstatuscarga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblStatusProgresso',
            fields=[
                ('id_status_progresso', models.SmallIntegerField(db_column='idstatusprogresso', primary_key=True, serialize=False)),
                ('str_descricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'verbose_name': 'Status Progresso',
                'verbose_name_plural': 'Status Progresso',
                'db_table': 'carga_org_lot.tblstatusprogresso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblStatusTokenEnvioCarga',
            fields=[
                ('id_status_token_envio_carga', models.SmallIntegerField(db_column='idstatustokenenviocarga', primary_key=True, serialize=False)),
                ('str_descricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'verbose_name': 'Status Token Envio Carga',
                'verbose_name_plural': 'Status Token Envio Carga',
                'db_table': 'carga_org_lot.tblstatustokenenviocarga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTipoCarga',
            fields=[
                ('id_tipo_carga', models.SmallIntegerField(db_column='idtipocarga', primary_key=True, serialize=False)),
                ('str_descricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo Carga',
                'verbose_name_plural': 'Tipos Carga',
                'db_table': 'carga_org_lot.tbltipocarga',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblTokenEnvioCarga',
            fields=[
                ('id_token_envio_carga', models.BigAutoField(db_column='idtokenenviocarga', primary_key=True, serialize=False)),
                ('str_token_retorno', models.CharField(db_column='strtokenretorno', max_length=1000)),
                ('dat_data_hora_inicio', models.DateTimeField(db_column='datdatahorainicio')),
                ('dat_data_hora_fim', models.DateTimeField(blank=True, db_column='datdatahorafim', null=True)),
            ],
            options={
                'verbose_name': 'Token Envio Carga',
                'verbose_name_plural': 'Tokens Envio Carga',
                'db_table': 'carga_org_lot.tbltokenenviocarga',
                'managed': False,
            },
        ),
    ]
