# Generated by Django 6.0.1 on 2026-01-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga_org_lot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcargapatriarca',
            options={'managed': True, 'verbose_name': 'Carga Patriarca', 'verbose_name_plural': 'Cargas Patriarca'},
        ),
        migrations.AlterModelOptions(
            name='tbldetalhestatuscarga',
            options={'managed': True, 'ordering': ['dat_registro'], 'verbose_name': 'Detalhe Status Carga', 'verbose_name_plural': 'Detalhes Status Carga'},
        ),
        migrations.AlterModelOptions(
            name='tbllotacao',
            options={'managed': True, 'verbose_name': 'Lotação', 'verbose_name_plural': 'Lotações'},
        ),
        migrations.AlterModelOptions(
            name='tbllotacaoinconsistencia',
            options={'managed': True, 'verbose_name': 'Inconsistência de Lotação', 'verbose_name_plural': 'Inconsistências de Lotação'},
        ),
        migrations.AlterModelOptions(
            name='tbllotacaojsonorgao',
            options={'managed': True, 'verbose_name': 'JSON Lotação por Órgão', 'verbose_name_plural': 'JSONs Lotação por Órgão'},
        ),
        migrations.AlterModelOptions(
            name='tbllotacaoversao',
            options={'managed': True, 'verbose_name': 'Versão de Lotação', 'verbose_name_plural': 'Versões de Lotação'},
        ),
        migrations.AlterModelOptions(
            name='tblorganogramajson',
            options={'managed': True, 'verbose_name': 'JSON Organograma', 'verbose_name_plural': 'JSONs Organograma'},
        ),
        migrations.AlterModelOptions(
            name='tblorganogramaversao',
            options={'managed': True, 'verbose_name': 'Versão de Organograma', 'verbose_name_plural': 'Versões de Organograma'},
        ),
        migrations.AlterModelOptions(
            name='tblorgaounidade',
            options={'managed': True, 'verbose_name': 'Órgão/Unidade', 'verbose_name_plural': 'Órgãos/Unidades'},
        ),
        migrations.AlterModelOptions(
            name='tblpatriarca',
            options={'managed': True, 'verbose_name': 'Patriarca', 'verbose_name_plural': 'Patriarcas'},
        ),
        migrations.AlterModelOptions(
            name='tblstatuscarga',
            options={'managed': True, 'verbose_name': 'Status Carga', 'verbose_name_plural': 'Status Carga'},
        ),
        migrations.AlterModelOptions(
            name='tblstatusprogresso',
            options={'managed': True, 'verbose_name': 'Status Progresso', 'verbose_name_plural': 'Status Progresso'},
        ),
        migrations.AlterModelOptions(
            name='tblstatustokenenviocarga',
            options={'managed': True, 'verbose_name': 'Status Token Envio Carga', 'verbose_name_plural': 'Status Token Envio Carga'},
        ),
        migrations.AlterModelOptions(
            name='tbltipocarga',
            options={'managed': True, 'verbose_name': 'Tipo Carga', 'verbose_name_plural': 'Tipos Carga'},
        ),
        migrations.AlterModelOptions(
            name='tbltokenenviocarga',
            options={'managed': True, 'verbose_name': 'Token Envio Carga', 'verbose_name_plural': 'Tokens Envio Carga'},
        ),
    ]
