# Generated by Django A.B.C on YYYY-MM-DD HH:MM
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),  # auth.User padrão
    ]

    operations = [
        # 1. Tabelas auxiliares
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('idaplicacao', models.AutoField(primary_key=True)),
                ('codigointerno', models.CharField(max_length=50, unique=True)),
                ('nomeaplicacao', models.CharField(max_length=200)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('isshowinportal', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tblaplicacao',
                'managed': True,
            },
        ),
        
        # 2. StatusUsuario
        migrations.CreateModel(
            name='TblStatusUsuario',
            fields=[
                ('idstatususuario', models.SmallIntegerField(db_column='idstatususuario', primary_key=True)),
                ('strdescricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'db_table': 'tblstatususuario',
                'managed': True,
            },
        ),
        
        # 3. TipoUsuario
        migrations.CreateModel(
            name='TblTipoUsuario',
            fields=[
                ('idtipousuario', models.SmallIntegerField(db_column='idtipousuario', primary_key=True)),
                ('strdescricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'db_table': 'tbltipousuario',
                'managed': True,
            },
        ),
        
        # 4. ClassificacaoUsuario
        migrations.CreateModel(
            name='TblClassificacaoUsuario',
            fields=[
                ('idclassificacaousuario', models.SmallIntegerField(db_column='idclassificacaousuario', primary_key=True)),
                ('strdescricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'db_table': 'tblclassificacaousuario',
                'managed': True,
            },
        ),
        
        # 5. UserProfile (extensão do auth.User)
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    related_name='profile',
                    to=settings.AUTH_USER_MODEL  # auth.User
                )),
                ('name', models.CharField(blank=True, db_column='strnome', max_length=200)),
                ('idstatususuario', models.ForeignKey(
                    db_column='idstatususuario',
                    default=1,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='accounts.TblStatusUsuario'
                )),
                ('idtipousuario', models.ForeignKey(
                    db_column='idtipousuario',
                    default=1,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='accounts.TblTipoUsuario'
                )),
                ('idclassificacaousuario', models.ForeignKey(
                    db_column='idclassificacaousuario',
                    default=1,
                    on_delete=django.db.models.deletion.PROTECT,
                    to='accounts.TblClassificacaoUsuario'
                )),
                ('idusuariocriacao', models.ForeignKey(
                    blank=True,
                    db_column='idusuariocriacao',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='profiles_criados',
                    to=settings.AUTH_USER_MODEL
                )),
                ('idusuarioalteracao', models.ForeignKey(
                    blank=True,
                    db_column='idusuarioalteracao',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='profiles_alterados',
                    to=settings.AUTH_USER_MODEL
                )),
                ('datacriacao', models.DateTimeField(auto_now_add=True, db_column='datacriacao')),
                ('data_alteracao', models.DateTimeField(blank=True, null=True, db_column='data_alteracao')),
            ],
            options={
                'db_table': 'tblusuario',
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'managed': True,
            },
        ),
        
        # 6. RBAC Models
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('aplicacao', models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Aplicacao')),
                ('codigoperfil', models.CharField(max_length=100)),
                ('nomeperfil', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'accounts_role',
                'constraints': [models.UniqueConstraint(fields=['aplicacao', 'codigoperfil'], name='uq_role_aplicacao_codigoperfil')],
            },
        ),
        
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aplicacao', models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Aplicacao')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Role')),
            ],
            options={
                'db_table': 'accounts_userrole',
                'constraints': [models.UniqueConstraint(fields=['user', 'aplicacao', 'role'], name='uq_userrole_user_aplicacao_role')],
            },
        ),
        
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aplicacao', models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Aplicacao')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'accounts_attribute',
                'constraints': [models.UniqueConstraint(fields=['user', 'aplicacao', 'key'], name='uq_attribute_user_aplicacao_key')],
            },
        ),
    ]
