# Generated by Django MIGRATION CONSOLIDATED for accounts
# Cria TODAS as tabelas do app accounts no schema public
from django.db import migrations, models
import django.contrib.auth.validators
from django.contrib.auth.models import PermissionsMixin  # ✅ ADICIONAR ESTA LINHA
from django.contrib.auth.base_user import AbstractBaseUser


def create_aplicacoes(apps, schema_editor):
    """
    Cria as aplicações essenciais do GPP Plataform
    """
    Aplicacao = apps.get_model('accounts', 'Aplicacao')
    
    aplicacoes_data = [
        {
            'idaplicacao': 1,
            'codigointerno': 'PORTAL',
            'nomeaplicacao': 'Portal GPP',
            'base_url': 'http://127.0.0.1:8000/portal/',
            'isshowinportal': False
        },
        {
            'idaplicacao': 2,
            'codigointerno': 'CARGA_ORG_LOT',
            'nomeaplicacao': 'Carga Única de Organograma e Lotação',
            'base_url': 'http://127.0.0.1:8000/carga_org_lot/',
            'isshowinportal': True
        },
        {
            'idaplicacao': 3,
            'codigointerno': 'ACOES_PNGI',
            'nomeaplicacao': 'Ações PNGI',
            'base_url': 'http://127.0.0.1:8000/acoes-pngi/',
            'isshowinportal': True
        }
    ]
    
    for data in aplicacoes_data:
        # Verificar se já existe (por codigointerno)
        if not Aplicacao.objects.filter(codigointerno=data['codigointerno']).exists():
            aplicacao = Aplicacao(**data)
            aplicacao.save(using=schema_editor.connection.alias)
            print(f"✅ Criada aplicação: {data['codigointerno']}")
        else:
            print(f"⚠️  Aplicação já existe: {data['codigointerno']}")

def delete_aplicacoes(apps, schema_editor):
        """Remove as aplicações criadas (para rollback)"""
        Aplicacao = apps.get_model('accounts', 'Aplicacao')
        codigos = ['PORTAL', 'CARGA_ORG_LOT', 'ACOES_PNGI']
        Aplicacao.objects.filter(codigointerno__in=codigos).delete()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),           # ✅ CORRETO
        ('acoes_pngi', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Tabela Aplicacao
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('idaplicacao', models.AutoField(primary_key=True)),
                ('codigointerno', models.CharField(max_length=50, unique=True)),
                ('nomeaplicacao', models.CharField(max_length=200)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('isshowinportal', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tblaplicacao',
                'managed': True,
            },
        ),

        # Tabela User (tblusuario)
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, db_column='idusuario')),
                ('password', models.CharField(db_column='strsenha', max_length=200)),
                ('last_login', models.DateTimeField(blank=True, null=True, db_column='last_login')),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False)),
                ('name', models.CharField(db_column='strnome', max_length=200)),
                ('email', models.EmailField(db_column='stremail', max_length=200, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True, db_column='date_joined')),
                ('idstatususuario', models.SmallIntegerField(db_column='idstatususuario', default=1)),
                ('idtipousuario', models.SmallIntegerField(db_column='idtipousuario', default=1)),
                ('idclassificacaousuario', models.SmallIntegerField(db_column='idclassificacaousuario', default=1)),
            ],
            options={
                'db_table': 'tblusuario',
                'managed': True,
            },
            bases=(AbstractBaseUser, PermissionsMixin),  # ✅ Sem 'models.'
        ),

        # Tabela Role (accounts_role)
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('nomeperfil', models.CharField(max_length=100)),
                ('codigoperfil', models.CharField(max_length=100)),
                ('aplicacao', models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=models.CASCADE, to='accounts.aplicacao')),
            ],
            options={
                'db_table': 'accounts_role',
            },
        ),

        # Tabela UserRole (accounts_userrole)
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('aplicacao', models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=models.CASCADE, to='accounts.aplicacao')),
                ('role', models.ForeignKey(on_delete=models.CASCADE, to='accounts.role')),
                ('user', models.ForeignKey(on_delete=models.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'accounts_userrole',
            },
        ),

        # Tabela Attribute (accounts_attribute)
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('aplicacao', models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=models.SET_NULL, to='accounts.aplicacao')),
                ('user', models.ForeignKey(on_delete=models.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'accounts_attribute',
            },
        ),
        
        # 2. INSERIR os dados das aplicações APÓS criar as tabelas
        migrations.RunPython(
            create_aplicacoes,
            delete_aplicacoes,
        ),

        # 3. Adicionar constraints únicos APÓS inserir dados
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('aplicacao', 'codigoperfil')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'aplicacao', 'role')},  # ← role (FK), não codigoperfil
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('user', 'aplicacao', 'key')},
        ),
    ]
