# Generated by Django 6.0.1 on 2026-01-13 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='idusuario', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='strnome', max_length=200)),
                ('email', models.EmailField(db_column='stremail', max_length=200, unique=True)),
                ('password', models.CharField(db_column='strsenha', max_length=200)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('date_joined', models.DateTimeField(blank=True, db_column='date_joined', null=True)),
                ('idstatususuario', models.SmallIntegerField(db_column='idstatususuario', default=1)),
                ('idtipousuario', models.SmallIntegerField(db_column='idtipousuario', default=1)),
                ('idclassificacaousuario', models.SmallIntegerField(db_column='idclassificacaousuario', default=1)),
            ],
            options={
                'db_table': 'tblusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('idaplicacao', models.AutoField(primary_key=True, serialize=False)),
                ('codigointerno', models.CharField(max_length=50, unique=True)),
                ('nomeaplicacao', models.CharField(max_length=200)),
                ('base_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblaplicacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeperfil', models.CharField(max_length=100)),
                ('codigoperfil', models.CharField(max_length=100)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aplicacao')),
            ],
            options={
                'unique_together': {('aplicacao', 'codigoperfil')},
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('aplicacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.aplicacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'aplicacao', 'key')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aplicacao')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'aplicacao', 'role')},
            },
        ),
    ]
