# Generated by Django 6.0.1 on 2026-02-27 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicacao',
            fields=[
                ('idaplicacao', models.AutoField(primary_key=True, serialize=False)),
                ('codigointerno', models.CharField(max_length=50, unique=True)),
                ('nomeaplicacao', models.CharField(max_length=200)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('isshowinportal', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tblaplicacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblClassificacaoUsuario',
            fields=[
                ('idclassificacaousuario', models.SmallIntegerField(db_column='idclassificacaousuario', primary_key=True, serialize=False)),
                ('strdescricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'verbose_name': 'Classificação de Usuário',
                'verbose_name_plural': 'Classificações de Usuários',
                'db_table': 'tblclassificacaousuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblStatusUsuario',
            fields=[
                ('idstatususuario', models.SmallIntegerField(db_column='idstatususuario', primary_key=True, serialize=False)),
                ('strdescricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'verbose_name': 'Status de Usuário',
                'verbose_name_plural': 'Status de Usuários',
                'db_table': 'tblstatususuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblTipoUsuario',
            fields=[
                ('idtipousuario', models.SmallIntegerField(db_column='idtipousuario', primary_key=True, serialize=False)),
                ('strdescricao', models.CharField(db_column='strdescricao', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Usuário',
                'verbose_name_plural': 'Tipos de Usuários',
                'db_table': 'tbltipousuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='idusuario', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='strnome', max_length=200)),
                ('email', models.EmailField(db_column='stremail', max_length=200, unique=True)),
                ('password', models.CharField(db_column='strsenha', max_length=200)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='date_joined')),
                ('datacriacao', models.DateTimeField(auto_now_add=True, db_column='datacriacao')),
                ('data_alteracao', models.DateTimeField(blank=True, db_column='data_alteracao', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('idusuarioalteracao', models.ForeignKey(blank=True, db_column='idusuarioalteracao', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_alterados', to=settings.AUTH_USER_MODEL)),
                ('idusuariocriacao', models.ForeignKey(blank=True, db_column='idusuariocriacao', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('idclassificacaousuario', models.ForeignKey(db_column='idclassificacaousuario', default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.tblclassificacaousuario')),
                ('idstatususuario', models.ForeignKey(db_column='idstatususuario', default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.tblstatususuario')),
                ('idtipousuario', models.ForeignKey(db_column='idtipousuario', default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.tbltipousuario')),
            ],
            options={
                'db_table': 'tblusuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeperfil', models.CharField(max_length=100)),
                ('codigoperfil', models.CharField(max_length=100)),
                ('aplicacao', models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.aplicacao')),
            ],
            options={
                'db_table': 'accounts_role',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacao', models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.aplicacao')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_userrole',
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('aplicacao', models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.aplicacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_attribute',
                'constraints': [models.UniqueConstraint(fields=('user', 'aplicacao', 'key'), name='uq_userrole_aplicacao_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('aplicacao', 'codigoperfil'), name='uq_role_aplicacao_codigoperfil'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'aplicacao', 'role'), name='uq_userrole_user_aplicacao_role'),
        ),
    ]
