# Generated by Django on 2026-02-27
from django.db import migrations

def create_roles_and_permissions(apps, schema_editor):
    """
    Cria roles e permissões para acoes_pngi baseado na matriz definitiva
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    
    # Limpar roles antigas se existirem
    Group.objects.filter(name__in=[
        'GESTOR_PNGI',
        'COORDENADOR_PNGI',
        'OPERADOR_ACAO',
        'CONSULTOR_PNGI'
    ]).delete()
    
    # Obter content_type para acoes_pngi
    try:
        acoes_ct = ContentType.objects.get(app_label='acoes_pngi', model='acoes')
    except ContentType.DoesNotExist:
        print("ContentType para acoes_pngi.Acoes não encontrado - pulando criação de permissões")
        return
    
    # ========== MODELOS E PERMISSÕES ==========
    
    # Mapear modelos para suas permissões
    models_permissions = {
        # CONFIGURAÇÕES - Nível 1 (Apenas GESTOR)
        'situacaoacao': {
            'read': ['view_situacaoacao'],
            'write': ['add_situacaoacao', 'change_situacaoacao', 'delete_situacaoacao']
        },
        'tipoentraveralerta': {
            'read': ['view_tipoentraveralerta'],
            'write': ['add_tipoentraveralerta', 'change_tipoentraveralerta', 'delete_tipoentraveralerta']
        },
        # CONFIGURAÇÕES - Nível 2 (GESTOR e COORDENADOR)
        'eixo': {
            'read': ['view_eixo'],
            'write': ['add_eixo', 'change_eixo', 'delete_eixo']
        },
        'vigenciapngi': {
            'read': ['view_vigenciapngi'],
            'write': ['add_vigenciapngi', 'change_vigenciapngi', 'delete_vigenciapngi']
        },
        'tipoanotacaoalinhamento': {
            'read': ['view_tipoanotacaoalinhamento'],
            'write': ['add_tipoanotacaoalinhamento', 'change_tipoanotacaoalinhamento', 'delete_tipoanotacaoalinhamento']
        },
        # OPERAÇÕES (GESTOR, COORDENADOR e OPERADOR)
        'acoes': {
            'read': ['view_acoes'],
            'write': ['add_acoes', 'change_acoes', 'delete_acoes']
        },
        'acaoprazo': {
            'read': ['view_acaoprazo'],
            'write': ['add_acaoprazo', 'change_acaoprazo', 'delete_acaoprazo']
        },
        'acaodestaque': {
            'read': ['view_acaodestaque'],
            'write': ['add_acaodestaque', 'change_acaodestaque', 'delete_acaodestaque']
        },
        'acaoanotacaoalinhamento': {
            'read': ['view_acaoanotacaoalinhamento'],
            'write': ['add_acaoanotacaoalinhamento', 'change_acaoanotacaoalinhamento', 'delete_acaoanotacaoalinhamento']
        },
        'usuarioresponsavel': {
            'read': ['view_usuarioresponsavel'],
            'write': ['add_usuarioresponsavel', 'change_usuarioresponsavel', 'delete_usuarioresponsavel']
        },
        'relacaoacaousuarioresponsavel': {
            'read': ['view_relacaoacaousuarioresponsavel'],
            'write': ['add_relacaoacaousuarioresponsavel', 'change_relacaoacaousuarioresponsavel', 'delete_relacaoacaousuarioresponsavel']
        },
    }
    
    # ========== CRIAR ROLES E ATRIBUIR PERMISSÕES ==========
    
    # 1. GESTOR_PNGI - Acesso total
    gestor = Group.objects.create(name='GESTOR_PNGI')
    for model_name, perms in models_permissions.items():
        for perm_codename in perms['read'] + perms['write']:
            try:
                perm = Permission.objects.get(
                    codename=perm_codename,
                    content_type__app_label='acoes_pngi'
                )
                gestor.permissions.add(perm)
            except Permission.DoesNotExist:
                print(f"Permissão {perm_codename} não encontrada")
    
    # Adicionar permissões de gestão de usuários
    user_perms = ['view_user', 'add_user', 'change_user', 'delete_user',
                  'view_group', 'add_group', 'change_group', 'delete_group']
    for perm_codename in user_perms:
        try:
            perm = Permission.objects.get(codename=perm_codename)
            gestor.permissions.add(perm)
        except Permission.DoesNotExist:
            pass
    
    # 2. COORDENADOR_PNGI - Acesso total às ações + configurações nível 2
    coordenador = Group.objects.create(name='COORDENADOR_PNGI')
    
    # Permissões de leitura em tudo
    for model_name, perms in models_permissions.items():
        for perm_codename in perms['read']:
            try:
                perm = Permission.objects.get(
                    codename=perm_codename,
                    content_type__app_label='acoes_pngi'
                )
                coordenador.permissions.add(perm)
            except Permission.DoesNotExist:
                pass
    
    # Permissões de escrita apenas em configurações nível 2 e operações
    nivel2_operacoes = ['eixo', 'vigenciapngi', 'tipoanotacaoalinhamento',
                        'acoes', 'acaoprazo', 'acaodestaque', 'acaoanotacaoalinhamento',
                        'usuarioresponsavel', 'relacaoacaousuarioresponsavel']
    
    for model_name in nivel2_operacoes:
        if model_name in models_permissions:
            for perm_codename in models_permissions[model_name]['write']:
                try:
                    perm = Permission.objects.get(
                        codename=perm_codename,
                        content_type__app_label='acoes_pngi'
                    )
                    coordenador.permissions.add(perm)
                except Permission.DoesNotExist:
                    pass
    
    # Leitura de usuários/roles
    for perm_codename in ['view_user', 'view_group']:
        try:
            perm = Permission.objects.get(codename=perm_codename)
            coordenador.permissions.add(perm)
        except Permission.DoesNotExist:
            pass
    
    # 3. OPERADOR_ACAO - Apenas operações em ações
    operador = Group.objects.create(name='OPERADOR_ACAO')
    
    # Permissões de leitura em tudo
    for model_name, perms in models_permissions.items():
        for perm_codename in perms['read']:
            try:
                perm = Permission.objects.get(
                    codename=perm_codename,
                    content_type__app_label='acoes_pngi'
                )
                operador.permissions.add(perm)
            except Permission.DoesNotExist:
                pass
    
    # Permissões de escrita apenas em operações (não configurações)
    operacoes = ['acoes', 'acaoprazo', 'acaodestaque', 'acaoanotacaoalinhamento',
                 'usuarioresponsavel', 'relacaoacaousuarioresponsavel']
    
    for model_name in operacoes:
        if model_name in models_permissions:
            for perm_codename in models_permissions[model_name]['write']:
                try:
                    perm = Permission.objects.get(
                        codename=perm_codename,
                        content_type__app_label='acoes_pngi'
                    )
                    operador.permissions.add(perm)
                except Permission.DoesNotExist:
                    pass
    
    # Leitura de usuários/roles
    for perm_codename in ['view_user', 'view_group']:
        try:
            perm = Permission.objects.get(codename=perm_codename)
            operador.permissions.add(perm)
        except Permission.DoesNotExist:
            pass
    
    # 4. CONSULTOR_PNGI - Apenas leitura
    consultor = Group.objects.create(name='CONSULTOR_PNGI')
    
    # Todas as permissões de leitura
    for model_name, perms in models_permissions.items():
        for perm_codename in perms['read']:
            try:
                perm = Permission.objects.get(
                    codename=perm_codename,
                    content_type__app_label='acoes_pngi'
                )
                consultor.permissions.add(perm)
            except Permission.DoesNotExist:
                pass
    
    # Leitura de usuários/roles
    for perm_codename in ['view_user', 'view_group']:
        try:
            perm = Permission.objects.get(codename=perm_codename)
            consultor.permissions.add(perm)
        except Permission.DoesNotExist:
            pass
    
    print("✅ Roles e permissões criadas com sucesso!")


def reverse_roles_and_permissions(apps, schema_editor):
    """
    Remove as roles criadas
    """
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=[
        'GESTOR_PNGI',
        'COORDENADOR_PNGI',
        'OPERADOR_ACAO',
        'CONSULTOR_PNGI'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(
            create_roles_and_permissions,
            reverse_roles_and_permissions
        ),
    ]
