# Generated by Django 6.0.1 on 2026-01-26 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='aplicacao',
            field=models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.aplicacao'),
        ),
    ]
