# Generated by Django A.I. Assistant - Dados Iniciais Domínio
from django.db import migrations

def load_status_usuario(apps, schema_editor):
    """Carrega status de usuário: Ativo/Inativo"""
    TblStatusUsuario = apps.get_model('accounts', 'TblStatusUsuario')
    data = [
        {'idstatususuario': 1, 'strdescricao': 'Ativo'},
        {'idstatususuario': 2, 'strdescricao': 'Inativo'},
    ]
    for item in data:
        TblStatusUsuario.objects.get_or_create(**item)

def load_tipo_usuario(apps, schema_editor):
    """Carrega tipo de usuário: Interno/Externo"""
    TblTipoUsuario = apps.get_model('accounts', 'TblTipoUsuario')
    data = [
        {'idtipousuario': 1, 'strdescricao': 'Interno'},
        {'idtipousuario': 2, 'strdescricao': 'Externo'},
    ]
    for item in data:
        TblTipoUsuario.objects.get_or_create(**item)

def load_classificacao_usuario(apps, schema_editor):
    """Carrega classificação padrão de usuário"""
    TblClassificacaoUsuario = apps.get_model('accounts', 'TblClassificacaoUsuario')
    data = [
        {'idclassificacaousuario': 1, 'strdescricao': 'Padrão'},
    ]
    for item in data:
        TblClassificacaoUsuario.objects.get_or_create(**item)

class Migration(migrations.Migration):
    """
    Migração inicial com dados de domínio obrigatórios para tblusuario.
    Dependências: 0001_initial (estrutura das tabelas)
    """
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_status_usuario, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(load_tipo_usuario, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(load_classificacao_usuario, reverse_code=migrations.RunPython.noop),
    ]
