# Generated by Django A.I. Assistant - Migração Consolidada Accounts
# accounts/0003_load_domain_aplicacoes_roles.py

from django.db import migrations

def load_all_domain_data(apps, schema_editor):
    """
    Migração consolidada: Carrega TODOS os dados iniciais obrigatórios em sequência
    
    ORDEM CRÍTICA:
    1. Status/Tipo/Classificação Usuario (dependências tblusuario)
    2. Aplicações (dependências básicas)
    3. Roles/Perfis (depende de aplicacao_id)
    4. Groups Django + Permissões acoes_pngi (segurança)
    """
    
    # 1. STATUS USUÁRIO
    TblStatusUsuario = apps.get_model('accounts', 'TblStatusUsuario')
    status_data = [
        {'idstatususuario': 1, 'strdescricao': 'Ativo'},
        {'idstatususuario': 2, 'strdescricao': 'Inativo'},
    ]
    for item in status_data:
        TblStatusUsuario.objects.get_or_create(**item)
    print("✅ Status Usuario carregados")
    
    # 2. TIPO USUÁRIO
    TblTipoUsuario = apps.get_model('accounts', 'TblTipoUsuario')
    tipo_data = [
        {'idtipousuario': 1, 'strdescricao': 'Interno'},
        {'idtipousuario': 2, 'strdescricao': 'Externo'},
    ]
    for item in tipo_data:
        TblTipoUsuario.objects.get_or_create(**item)
    print("✅ Tipo Usuario carregados")
    
    # 3. CLASSIFICAÇÃO USUÁRIO
    TblClassificacaoUsuario = apps.get_model('accounts', 'TblClassificacaoUsuario')
    classificacao_data = [
        {'idclassificacaousuario': 1, 'strdescricao': 'Padrão'},
    ]
    for item in classificacao_data:
        TblClassificacaoUsuario.objects.get_or_create(**item)
    print("✅ Classificação Usuario carregada")
    
    # 4. APLICAÇÕES (ÚNICA inserção - sem duplicação)
    Aplicacao = apps.get_model('accounts', 'Aplicacao')
    aplicacoes_data = [
        {
            'idaplicacao': 1,
            'codigointerno': 'PORTAL',
            'nomeaplicacao': 'Portal GPP',
            'base_url': 'http://127.0.0.1:8000/portal/',
            'isshowinportal': False
        },
        {
            'idaplicacao': 2,
            'codigointerno': 'CARGA_ORG_LOT',
            'nomeaplicacao': 'Carga Única de Organograma e Lotação',
            'base_url': 'http://127.0.0.1:8000/carga_org_lot/',
            'isshowinportal': True
        },
        {
            'idaplicacao': 3,
            'codigointerno': 'ACOES_PNGI',
            'nomeaplicacao': 'Ações PNGI',
            'base_url': 'http://127.0.0.1:8000/acoes-pngi/',
            'isshowinportal': True
        }
    ]
    for data in aplicacoes_data:
        if not Aplicacao.objects.filter(codigointerno=data['codigointerno']).exists():
            aplicacao = Aplicacao(**data)
            aplicacao.save(using=schema_editor.connection.alias)
            print(f"✅ Aplicação criada: {data['codigointerno']}")
        else:
            print(f"⚠️ Aplicação já existe: {data['codigointerno']}")
    
    # 5. ROLES/PERFIS (depende de aplicacao_id)
    Role = apps.get_model('accounts', 'Role')
    roles_data = [
        # PORTAL (aplicacao_id=1)
        {'id': 1, 'nomeperfil': 'Usuario do Portal', 'codigoperfil': 'USER_PORTAL', 'aplicacao_id': 1},
        {'id': 4, 'nomeperfil': 'Gestor do Portal', 'codigoperfil': 'GESTOR_PORTAL', 'aplicacao_id': 1},
        
        # CARGA_ORG_LOT (aplicacao_id=2)
        {'id': 2, 'nomeperfil': 'Gestor Carga Org/Lot', 'codigoperfil': 'GESTOR_CARGA', 'aplicacao_id': 2},
        {'id': 20, 'nomeperfil': 'Coordenador - Gerencia Configurações', 'codigoperfil': 'COORDENADOR_CARGA', 'aplicacao_id': 2},
        {'id': 21, 'nomeperfil': 'Analista - Upload e Validação', 'codigoperfil': 'ANALISTA_CARGA', 'aplicacao_id': 2},
        {'id': 22, 'nomeperfil': 'Consultor - Apenas Leitura', 'codigoperfil': 'VISUALIZADOR_CARGA', 'aplicacao_id': 2},
        
        # ACOES_PNGI (aplicacao_id=3)
        {'id': 3, 'nomeperfil': 'Gestor Acoes PNGI', 'codigoperfil': 'GESTOR_PNGI', 'aplicacao_id': 3},
        {'id': 5, 'nomeperfil': 'Coordenador - Gerencia Configurações', 'codigoperfil': 'COORDENADOR_PNGI', 'aplicacao_id': 3},
        {'id': 6, 'nomeperfil': 'Operador - Apenas Ações', 'codigoperfil': 'OPERADOR_ACAO', 'aplicacao_id': 3},
        {'id': 7, 'nomeperfil': 'Consultor - Apenas Leitura', 'codigoperfil': 'CONSULTOR_PNGI', 'aplicacao_id': 3},
    ]
    for item in roles_data:
        Role.objects.get_or_create(id=item['id'], defaults=item)
    print("✅ Todas as Roles/Perfis carregadas")
    
    # 6. DJANGO GROUPS + PERMISSÕES acoes_pngi
    create_pngi_groups_and_permissions(apps, schema_editor)

def create_pngi_groups_and_permissions(apps, schema_editor):
    """Matriz PNGI CORRETA - COORD tem N2+OPERAÇÕES write"""
    from django.contrib.contenttypes.models import ContentType
    from django.contrib.auth.models import Permission, Group
    
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    Group = apps.get_model('auth', 'Group')
    
    # DELETE groups existentes PNGI
    pngi_groups = ['GESTOR_PNGI', 'COORDENADOR_PNGI', 'OPERADOR_ACAO', 'CONSULTOR_PNGI']
    Group.objects.filter(name__in=pngi_groups).delete()
    
    try:
        acoes_ct = ContentType.objects.get(app_label='acoes_pngi', model='acoes')
    except ContentType.DoesNotExist:
        print("⚠️ ContentType acoes_pngi.Acoes não encontrado - pulando")
        return
    
    # MAPA EXATO MATRIZ (N1, N2, OPERAÇÕES)
    models_permissions = {
        # NÍVEL 1 (GESTOR write)
        'situacaoacao': {'read': ['view_situacaoacao'], 'write': ['add_situacaoacao', 'change_situacaoacao', 'delete_situacaoacao']},
        'tipoentraveralerta': {'read': ['view_tipoentraveralerta'], 'write': ['add_tipoentraveralerta', 'change_tipoentraveralerta', 'delete_tipoentraveralerta']},
        
        # NÍVEL 2 (GESTOR+COORD write)
        'eixo': {'read': ['view_eixo'], 'write': ['add_eixo', 'change_eixo', 'delete_eixo']},
        'vigenciapngi': {'read': ['view_vigenciapngi'], 'write': ['add_vigenciapngi', 'change_vigenciapngi', 'delete_vigenciapngi']},
        'tipoanotacaoalinhamento': {'read': ['view_tipoanotacaoalinhamento'], 'write': ['add_tipoanotacaoalinhamento', 'change_tipoanotacaoalinhamento', 'delete_tipoanotacaoalinhamento']},
        
        # OPERAÇÕES (GESTOR+COORD+OPERADOR write)
        'acoes': {'read': ['view_acoes'], 'write': ['add_acoes', 'change_acoes', 'delete_acoes']},
        'acaoprazo': {'read': ['view_acaoprazo'], 'write': ['add_acaoprazo', 'change_acaoprazo', 'delete_acaoprazo']},
        'acaodestaque': {'read': ['view_acaodestaque'], 'write': ['add_acaodestaque', 'change_acaodestaque', 'delete_acaodestaque']},
        'acaoanotacaoalinhamento': {'read': ['view_acaoanotacaoalinhamento'], 'write': ['add_acaoanotacaoalinhamento', 'change_acaoanotacaoalinhamento', 'delete_acaoanotacaoalinhamento']},
        'usuarioresponsavel': {'read': ['view_usuarioresponsavel'], 'write': ['add_usuarioresponsavel', 'change_usuarioresponsavel', 'delete_usuarioresponsavel']},
        'relacaoacaousuarioresponsavel': {'read': ['view_relacaoacaousuarioresponsavel'], 'write': ['add_relacaoacaousuarioresponsavel', 'change_relacaoacaousuarioresponsavel', 'delete_relacaoacaousuarioresponsavel']},
    }
    
    # FUNÇÕES HELPER
    def add_model_perms(group, model_names, read=True, write=False):
        for model_name in model_names:
            if model_name in models_permissions:
                perms_list = []
                if read: perms_list.extend(models_permissions[model_name]['read'])
                if write: perms_list.extend(models_permissions[model_name]['write'])
                for codename in perms_list:
                    try:
                        perm = Permission.objects.get(codename=codename, content_type=acoes_ct)
                        group.permissions.add(perm)
                    except Permission.DoesNotExist:
                        pass
    
    def add_auth_perms(group, codenames):
        for codename in codenames:
            try:
                perm = Permission.objects.get(codename=codename)
                group.permissions.add(perm)
            except Permission.DoesNotExist:
                pass
    
    all_models = list(models_permissions.keys())
    
    # 1. GESTOR_PNGI: TOTAL + auth full
    gestor = Group.objects.create(name='GESTOR_PNGI')
    add_model_perms(gestor, all_models, read=True, write=True)
    add_auth_perms(gestor, ['add_user', 'change_user', 'delete_user', 'view_user', 
                           'add_group', 'change_group', 'delete_group', 'view_group'])
    
    # 2. COORDENADOR_PNGI: read ALL + write (N2 + OPERAÇÕES)
    coord = Group.objects.create(name='COORDENADOR_PNGI')
    add_model_perms(coord, all_models, read=True, write=False)  # Read todos
    coord_write = ['eixo', 'vigenciapngi', 'tipoanotacaoalinhamento'] + ['acoes', 'acaoprazo', 'acaodestaque', 'acaoanotacaoalinhamento', 'usuarioresponsavel', 'relacaoacaousuarioresponsavel']
    add_model_perms(coord, coord_write, read=False, write=True)
    add_auth_perms(coord, ['view_user', 'view_group'])
    
    # 3. OPERADOR_ACAO: read ALL + write OPERAÇÕES apenas
    operador = Group.objects.create(name='OPERADOR_ACAO')
    add_model_perms(operador, all_models, read=True, write=False)
    op_write = ['acoes', 'acaoprazo', 'acaodestaque', 'acaoanotacaoalinhamento', 'usuarioresponsavel', 'relacaoacaousuarioresponsavel']
    add_model_perms(operador, op_write, read=False, write=True)
    add_auth_perms(operador, ['view_user', 'view_group'])
    
    # 4. CONSULTOR_PNGI: read ALL apenas
    consultor = Group.objects.create(name='CONSULTOR_PNGI')
    add_model_perms(consultor, all_models, read=True, write=False)
    add_auth_perms(consultor, ['view_user', 'view_group'])
    
    print("✅ Matriz PNGI 100% OK: GESTOR(total), COORD(N2+ops), OPERADOR(ops), CONSULTOR(read)")



def reverse_migration(apps, schema_editor):
    """Rollback: remove apenas dados criados por esta migração"""
    from django.contrib.auth.models import Group
    
    Group = apps.get_model('auth', 'Group')
    pngi_groups = ['GESTOR_PNGI', 'COORDENADOR_PNGI', 'OPERADOR_ACAO', 'CONSULTOR_PNGI']
    Group.objects.filter(name__in=pngi_groups).delete()
    
    # Não remove domain tables/aplicacoes/roles por serem dados estruturais críticos
    print("⚠️ Rollback parcial: apenas Groups PNGI removidos (domain data preservado)")


class Migration(migrations.Migration):
    """
    MIGRAÇÃO CONSOLIDADA ACCOUNTS - TODOS DADOS INICIAIS OBRIGATÓRIOS
    
    ✅ Status/Tipo/Classificação Usuario
    ✅ 3 Aplicações GPP Platform  
    ✅ 10 Roles/Perfis (todas aplicações)
    ✅ 4 Groups Django + Permissões acoes_pngi
    
    Dependências: 0001_initial ou 0002 (estrutura tabelas)
    """
    
    dependencies = [
        ('accounts', '0001_initial'),  # ou '0002_load_domain_tables' se existir
    ]

    operations = [
        migrations.RunPython(
            load_all_domain_data,
            reverse_code=reverse_migration
        ),
    ]
