# Generated by Django A.I. Assistant - Aplicações + Perfis PNGI
from django.db import migrations

def load_aplicacoes(apps, schema_editor):
    """Carrega as 3 aplicações principais"""
    Aplicacao = apps.get_model('accounts', 'Aplicacao')
    data = [
        {
            'idaplicacao': 1,
            'codigointerno': 'PORTAL',
            'nomeaplicacao': 'Portal GPP',
            'base_url': 'http://127.0.0.1:8000/portal/',
            'isshowinportal': False
        },
        {
            'idaplicacao': 2,
            'codigointerno': 'CARGA_ORG_LOT',
            'nomeaplicacao': 'Carga Única de Organograma e Lotação',
            'base_url': 'http://127.0.0.1:8000/carga_org_lot/',
            'isshowinportal': True
        },
        {
            'idaplicacao': 3,
            'codigointerno': 'ACOES_PNGI',
            'nomeaplicacao': 'Ações PNGI',
            'base_url': 'http://127.0.0.1:8000/acoes-pngi/',
            'isshowinportal': True
        },
    ]
    for item in data:
        Aplicacao.objects.get_or_create(idaplicacao=item['idaplicacao'], defaults=item)

def load_roles(apps, schema_editor):
    """Carrega 10 perfis conforme matriz de permissões"""
    Role = apps.get_model('accounts', 'Role')
    data = [
        # PORTAL (aplicacao_id=1)
        {'id': 1, 'nomeperfil': 'Usuario do Portal', 'codigoperfil': 'USER_PORTAL', 'aplicacao_id': 1},
        {'id': 4, 'nomeperfil': 'Gestor do Portal', 'codigoperfil': 'GESTOR_PORTAL', 'aplicacao_id': 1},
        
        # CARGA_ORG_LOT (aplicacao_id=2)
        {'id': 2, 'nomeperfil': 'Gestor Carga Org/Lot', 'codigoperfil': 'GESTOR_CARGA', 'aplicacao_id': 2},
        {'id': 20, 'nomeperfil': 'Coordenador - Gerencia Configurações', 'codigoperfil': 'COORDENADOR_CARGA', 'aplicacao_id': 2},
        {'id': 21, 'nomeperfil': 'Analista - Upload e Validação', 'codigoperfil': 'ANALISTA_CARGA', 'aplicacao_id': 2},
        {'id': 22, 'nomeperfil': 'Consultor - Apenas Leitura', 'codigoperfil': 'VISUALIZADOR_CARGA', 'aplicacao_id': 2},
        
        # ACOES_PNGI (aplicacao_id=3) - MATRIZ OFICIAL
        {'id': 3, 'nomeperfil': 'Gestor Acoes PNGI', 'codigoperfil': 'GESTOR_PNGI', 'aplicacao_id': 3},
        {'id': 5, 'nomeperfil': 'Coordenador - Gerencia Configurações', 'codigoperfil': 'COORDENADOR_PNGI', 'aplicacao_id': 3},
        {'id': 6, 'nomeperfil': 'Operador - Apenas Ações', 'codigoperfil': 'OPERADOR_ACAO', 'aplicacao_id': 3},
        {'id': 7, 'nomeperfil': 'Consultor - Apenas Leitura', 'codigoperfil': 'CONSULTOR_PNGI', 'aplicacao_id': 3},
    ]
    for item in data:
        Role.objects.get_or_create(id=item['id'], defaults=item)

class Migration(migrations.Migration):
    """
    Migração com dados estruturais: Aplicações + Perfis.
    Dependências: 0002_load_domain_tables
    """
    dependencies = [
        ('accounts', '0002_load_domain_tables'),
    ]

    operations = [
        migrations.RunPython(load_aplicacoes, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(load_roles, reverse_code=migrations.RunPython.noop),
    ]
