# Generated by Django 6.0.1 on 2026-01-26 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_attribute_aplicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='aplicacao',
            field=models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.aplicacao'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='aplicacao',
            field=models.ForeignKey(db_column='aplicacao_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.aplicacao'),
        ),
    ]
