# Generated by Django 6.0.1 on 2026-03-06 18:23

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_load_domain_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idclassificacaousuario',
            field=models.ForeignKey(db_column='idclassificacaousuario', default=accounts.models.default_classificacao_usuari, on_delete=django.db.models.deletion.PROTECT, to='accounts.tblclassificacaousuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idstatususuario',
            field=models.ForeignKey(db_column='idstatususuario', default=accounts.models.default_status_usuario, on_delete=django.db.models.deletion.PROTECT, to='accounts.tblstatususuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idtipousuario',
            field=models.ForeignKey(db_column='idtipousuario', default=accounts.models.default_tipo_usuario, on_delete=django.db.models.deletion.PROTECT, to='accounts.tbltipousuario'),
        ),
    ]
