# Generated by Django 6.0.1 on 2026-01-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_role_aplicacao_alter_userrole_aplicacao'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attribute',
            table='accounts_attribute',
        ),
        migrations.AlterModelTable(
            name='role',
            table='accounts_role',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='accounts_userrole',
        ),
    ]
