# accounts/migrations/0005_populate_auth_groups.py
# Generated by Django 6.0.1 on 2026-02-26 12:49

from django.db import migrations
from django.contrib.auth.models import Group


def criar_grupos_django(apps, schema_editor):
    """
    Mapeia accounts_role → auth_group para usar sistema nativo do Django.
    
    Estratégia:
    - Para cada Role em accounts_role, criar um Group em auth_group
    - Nome do grupo: {aplicacao_codigo}_{role_codigoperfil}
    - Exemplo: ACOES_PNGI_GESTOR_PNGI, ACOES_PNGI_COORDENADOR_PNGI
    """
    Role = apps.get_model('accounts', 'Role')
    Aplicacao = apps.get_model('accounts', 'Aplicacao')
    
    roles = Role.objects.select_related('aplicacao').all()
    
    grupos_criados = 0
    grupos_existentes = 0
    
    for role in roles:
        # Nome padrão: {APP_CODE}_{ROLE_CODE}
        group_name = f"{role.aplicacao.codigointerno}_{role.codigoperfil}"
        
        group, created = Group.objects.get_or_create(name=group_name)
        
        if created:
            grupos_criados += 1
            print(f"✅ Grupo criado: {group_name} (Role ID: {role.id})")
        else:
            grupos_existentes += 1
            print(f"ℹ️  Grupo já existe: {group_name}")
    
    print(f"\n📊 Resumo:")
    print(f"   - Grupos criados: {grupos_criados}")
    print(f"   - Grupos já existentes: {grupos_existentes}")
    print(f"   - Total de roles processadas: {roles.count()}")


def reverter_grupos_django(apps, schema_editor):
    """
    Reverte a criação dos grupos (opcional - cuidado em produção).
    """
    Role = apps.get_model('accounts', 'Role')
    
    roles = Role.objects.select_related('aplicacao').all()
    
    for role in roles:
        group_name = f"{role.aplicacao.codigointerno}_{role.codigoperfil}"
        try:
            group = Group.objects.get(name=group_name)
            group.delete()
            print(f"🗑️  Grupo removido: {group_name}")
        except Group.DoesNotExist:
            print(f"⚠️  Grupo não encontrado: {group_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_attribute_table_alter_role_table_and_more'),
    ]

    operations = [
        migrations.RunPython(
            criar_grupos_django,
            reverse_code=reverter_grupos_django
        ),
    ]
