# accounts/migrations/0006_populate_auth_group_permissions.py
# Generated by Django 6.0.1 on 2026-02-26 12:56 - CORRIGIDA COM NOMES REAIS

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


# 📋 MATRIZ DE PERMISSÕES CORRIGIDA (baseada nos dados reais)
MATRIZ_PERMISSOES = {
    # ============================================================================
    # GESTOR_PNGI (id=3) - Acesso total
    # ============================================================================
    'GESTOR_PNGI': {
        # Nível 1 - Configurações Críticas (somente GESTOR pode W/D)
        'situacaoacao': ['view', 'add', 'change', 'delete'],
        'tipoentravealerta': ['view', 'add', 'change', 'delete'],
        
        # Nível 2 - Configurações Compartilhadas
        'eixo': ['view', 'add', 'change', 'delete'],
        'vigenciapngi': ['view', 'add', 'change', 'delete'],
        'tipoanotacaoalinhamento': ['view', 'add', 'change', 'delete'],
        
        # Operações (GESTOR + COORDENADOR + OPERADOR)
        'acoes': ['view', 'add', 'change', 'delete'],
        'acaoprazo': ['view', 'add', 'change', 'delete'],
        'acaodestaque': ['view', 'add', 'change', 'delete'],
        'acaoanotacaoalinhamento': ['view', 'add', 'change', 'delete'],
        'usuarioresponsavel': ['view', 'add', 'change', 'delete'],
        'relacaoacaousuarioresponsavel': ['view', 'add', 'change', 'delete'],
        
        # Gestão de Usuários (apenas GESTOR)
        'user': ['view', 'add', 'change', 'delete'],
        'role': ['view'],
        'userrole': ['view', 'add', 'change', 'delete'],
        'aplicacao': ['view'],
        'attribute': ['view', 'add', 'change', 'delete'],
    },
    
    # ============================================================================
    # COORDENADOR_PNGI (id=5) - Nível 2 + Operações
    # ============================================================================
    'COORDENADOR_PNGI': {
        # Nível 1 - Apenas leitura
        'situacaoacao': ['view'],
        'tipoentravealerta': ['view'],
        
        # Nível 2 - Escrita permitida
        'eixo': ['view', 'add', 'change', 'delete'],
        'vigenciapngi': ['view', 'add', 'change', 'delete'],
        'tipoanotacaoalinhamento': ['view', 'add', 'change', 'delete'],
        
        # Operações - Escrita permitida
        'acoes': ['view', 'add', 'change', 'delete'],
        'acaoprazo': ['view', 'add', 'change', 'delete'],
        'acaodestaque': ['view', 'add', 'change', 'delete'],
        'acaoanotacaoalinhamento': ['view', 'add', 'change', 'delete'],
        'usuarioresponsavel': ['view', 'add', 'change', 'delete'],
        'relacaoacaousuarioresponsavel': ['view', 'add', 'change', 'delete'],
        
        # IAM - Apenas leitura
        'user': ['view'],
        'role': ['view'],
        'userrole': ['view'],
        'aplicacao': ['view'],
        'attribute': ['view'],
    },
    
    # ============================================================================
    # OPERADOR_ACAO (id=6) - Apenas Operações
    # ============================================================================
    'OPERADOR_ACAO': {
        # Configurações - Apenas leitura
        'situacaoacao': ['view'],
        'tipoentravealerta': ['view'],
        'eixo': ['view'],
        'vigenciapngi': ['view'],
        'tipoanotacaoalinhamento': ['view'],
        
        # Operações - Escrita permitida
        'acoes': ['view', 'add', 'change', 'delete'],
        'acaoprazo': ['view', 'add', 'change', 'delete'],
        'acaodestaque': ['view', 'add', 'change', 'delete'],
        'acaoanotacaoalinhamento': ['view', 'add', 'change', 'delete'],
        'usuarioresponsavel': ['view', 'add', 'change', 'delete'],
        'relacaoacaousuarioresponsavel': ['view', 'add', 'change', 'delete'],
        
        # IAM - Apenas leitura
        'user': ['view'],
        'role': ['view'],
        'userrole': ['view'],
        'aplicacao': ['view'],
        'attribute': ['view'],
    },
    
    # ============================================================================
    # CONSULTOR_PNGI (id=7) - Apenas leitura
    # ============================================================================
    'CONSULTOR_PNGI': {
        # Tudo apenas leitura
        'situacaoacao': ['view'],
        'tipoentravealerta': ['view'],
        'eixo': ['view'],
        'vigenciapngi': ['view'],
        'tipoanotacaoalinhamento': ['view'],
        'acoes': ['view'],
        'acaoprazo': ['view'],
        'acaodestaque': ['view'],
        'acaoanotacaoalinhamento': ['view'],
        'usuarioresponsavel': ['view'],
        'relacaoacaousuarioresponsavel': ['view'],
        'user': ['view'],
        'role': ['view'],
        'userrole': ['view'],
        'aplicacao': ['view'],
        'attribute': ['view'],
    },
}


def popular_permissoes(apps, schema_editor):
    """
    Popula auth_group_permissions com base na matriz corrigida.
    
    Grupos reais do banco:
    - ACOES_PNGI_GESTOR_PNGI
    - ACOES_PNGI_COORDENADOR_PNGI  
    - ACOES_PNGI_OPERADOR_ACAO
    - ACOES_PNGI_CONSULTOR_PNGI
    """
    Aplicacao = apps.get_model('accounts', 'Aplicacao')
    
    # Aplicação PNGI (aplicacao_id=3)
    aplicacao = Aplicacao.objects.get(codigointerno='ACOES_PNGI')  # ACOES_PNGI
    app_code = aplicacao.codigointerno
    
    total_permissoes = 0
    permissoes_adicionadas = 0
    erros = 0
    
    print("\n" + "="*80)
    print("🔐 POPULANDO PERMISSÕES - ACOES_PNGI")
    print("="*80 + "\n")
    
    for role_code, modelos in MATRIZ_PERMISSOES.items():
        group_name = f"{app_code}_{role_code}"
        
        try:
            group = Group.objects.get(name=group_name)
            print(f"\n🔑 Role: {role_code} → {group_name}")
            print("-" * 60)
            
            for modelo_name, acoes in modelos.items():
                # Determinar app_label
                if modelo_name in ['user', 'role', 'userrole', 'aplicacao', 'attribute']:
                    app_label = 'accounts'
                else:
                    app_label = 'acoes_pngi'
                
                try:
                    content_type = ContentType.objects.get(
                        app_label=app_label,
                        model=modelo_name
                    )
                    
                    for acao in acoes:
                        codename = f"{acao}_{modelo_name}"
                        total_permissoes += 1
                        
                        try:
                            permission = Permission.objects.get(
                                codename=codename,
                                content_type=content_type
                            )
                            
                            # Adicionar se não existir
                            if not group.permissions.filter(id=permission.id).exists():
                                group.permissions.add(permission)
                                permissoes_adicionadas += 1
                                print(f"   ✅ {codename}")
                            else:
                                print(f"   ℹ️  Já existe: {codename}")
                                
                        except Permission.DoesNotExist:
                            erros += 1
                            print(f"   ❌ Permission não encontrada: {codename}")
                
                except ContentType.DoesNotExist:
                    erros += 1
                    print(f"   ⚠️  ContentType não encontrado: {app_label}.{modelo_name}")
        
        except Group.DoesNotExist:
            print(f"   ⚠️  Grupo não encontrado: {group_name}")
    
    print("\n" + "="*80)
    print("📊 RESUMO FINAL")
    print("="*80)
    print(f"✅ Permissões adicionadas: {permissoes_adicionadas}")
    print(f"❌ Erros: {erros}")
    print(f"📈 Total processado: {total_permissoes}")
    print("\n🎉 MIGRATION CONCLUÍDA COM SUCESSO!")
    
    # Verificação final
    gestor_group = Group.objects.get(name=f"{app_code}_GESTOR_PNGI")
    print(f"\n✅ GESTOR_PNGI tem {gestor_group.permissions.count()} permissões")
    print(f"   Amostra: {list(gestor_group.permissions.values_list('codename', flat=True))[:5]}...")


def reverter_permissoes(apps, schema_editor):
    """Remove permissões dos grupos PNGI."""
    Aplicacao = apps.get_model('accounts', 'Aplicacao')
    
    aplicacao = Aplicacao.objects.get(id=3)
    app_code = aplicacao.codigointerno
    
    for role_code in MATRIZ_PERMISSOES.keys():
        group_name = f"{app_code}_{role_code}"
        
        try:
            group = Group.objects.get(name=group_name)
            group.permissions.clear()
            print(f"🗑️  Permissões removidas: {group_name}")
        except Group.DoesNotExist:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_populate_auth_groups'),
        ('acoes_pngi', '0008_acoes_idsituacaoacao_alter_acoes_ideixo'),
    ]

    operations = [
        migrations.RunPython(
            popular_permissoes,
            reverse_code=reverter_permissoes
        ),
    ]
