# accounts/migrations/0007_remove_rolepermission_model.py
# Generated by Django 6.0.1 on 2026-02-26 10:07 - VERSÃO SEM ERRO

from django.db import migrations


def verificar_rolepermission(apps, schema_editor):
    """
    Verificação final - RolePermission já foi removida.
    """
    print("\n" + "="*60)
    print("🎯 MIGRAÇÃO IAM FINALIZADA")
    print("="*60)
    print("✅ auth_group populado com 4 roles PNGI")
    print("✅ auth_group_permissions com matriz completa")
    print("✅ RolePermission já removida anteriormente")
    print("\n🚀 Sistema pronto para AuthorizationService nativo!")
    print("="*60 + "\n")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_populate_auth_group_permissions'),
    ]

    operations = [
        migrations.RunPython(
            verificar_rolepermission,
            reverse_code=migrations.RunPython.noop
        ),
        # RolePermission já foi removida do models.py
        # Esta migration apenas marca como aplicada
    ]
