# Generated by Django 6.0.1 on 2026-02-27 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100, unique=True)),
                ('client_secret_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('aplicacao', models.OneToOneField(db_column='aplicacao_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.aplicacao')),
            ],
            options={
                'db_table': 'db_service_appclient',
            },
        ),
    ]
