# Generated by Django 6.0.1 on 2026-01-26 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_attribute_table_alter_role_table_and_more'),
        ('db_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appclient',
            name='aplicacao',
            field=models.OneToOneField(db_column='aplicacao_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.aplicacao'),
        ),
        migrations.AlterModelTable(
            name='appclient',
            table='db_service_appclient',
        ),
    ]
