"""
Django settings for gpp_plataform project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


import os

# Hosts/IPs para desenvolvimento (Ubuntu/WSL + Windows)
HOST_IP = os.getenv('DJANGO_HOST_IP', '172.22.176.1')  # Seu IP do Ubuntu
FRONTEND_URLS = [
    f"http://{HOST_IP}:3000",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

# Hosts Django
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    HOST_IP,
    '*',  # Só dev
]

# CORS/CSRF para Next.js (Ubuntu)
CORS_ALLOWED_ORIGINS = FRONTEND_URLS
CSRF_TRUSTED_ORIGINS = FRONTEND_URLS




# Configuração de sessão
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24 horas

# Messages framework
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'


TEMPLATES = [{
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': [BASE_DIR / '../templates'],
    'APP_DIRS': True,
    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.debug',
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
    },
}]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zi_0xgun9-=se!8anfq0cian(+e%*%-k(f-6xwxr8qe^85(10p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '172.22.176.1',      # ← SEU IP DO UBUNTU
    '*',                  # ← TEMPORÁRIO para desenvolvimento
]


# Application definition

INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceiros
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    
    # Apps do projeto
    'common',
    'accounts',
    'auth_service',
    'portal',
    'carga_org_lot',
    'acoes_pngi',  # ← ADICIONAR AQUI
    'db_service',
]
    

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'common.middleware.app_context.AppContextMiddleware',
]

ROOT_URLCONF = 'gpp_plataform.urls'

WSGI_APPLICATION = 'gpp_plataform.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

"""DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}"""

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'gpp_plataform',
        #'USER': 'gpp_connect', # substituir pelo seu usuário do banco
        #'PASSWORD': 'gpp@conn!01', # substituir pela sua senha do banco
        'USER': 'postgres', # substituir pelo seu usuário do banco
        'PASSWORD': 'GPP_bd@202601', # substituir pela sua senha do banco
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

AUTH_USER_MODEL = 'accounts.User'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Configurar Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Configuração do SIMPLE_JWT
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    'AUTH_HEADER_TYPES': ('Bearer',),

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),

    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}


AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Configurações de Login
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'



CORS_ALLOW_CREDENTIALS = True

# Session Configuration
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # True em produção com HTTPS
SESSION_COOKIE_AGE = 86400  # 24 horas

CSRF_COOKIE_HTTPONLY = False  # Permitir JS ler o token
CSRF_COOKIE_SAMESITE = 'Lax'



# =========================================================================
# CONFIGURAÇÕES DE COMUNICAÇÃO ENTRE APLICAÇÕES
# =========================================================================

# Porta do portal (para apps filhas acessarem)
PORTAL_PORT = os.getenv('PORTAL_PORT', '8000')

# Credenciais do Service Account (para apps acessarem APIs do Portal)
PORTAL_SERVICE_EMAIL = os.getenv('PORTAL_SERVICE_EMAIL', '')
PORTAL_SERVICE_PASSWORD = os.getenv('PORTAL_SERVICE_PASSWORD', '')

# Cache para tokens (já existe, mas certifique-se de ter configurado)
if 'CACHES' not in locals():
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'gpp-plataform-cache',
            'TIMEOUT': 3600,  # 1 hora
        }
    }

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'acoes_pngi.services.portal_auth': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
