# Generated by Django 6.0.1 on 2026-01-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes_pngi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='eixo',
            table_comment='Schema: acoes_pngi',
        ),
        migrations.AlterModelTableComment(
            name='situacaoacao',
            table_comment='Schema: acoes_pngi',
        ),
        migrations.AlterModelTableComment(
            name='vigenciapngi',
            table_comment='Schema: acoes_pngi',
        ),
        migrations.AlterModelTable(
            name='eixo',
            table='tbleixos',
        ),
        migrations.AlterModelTable(
            name='situacaoacao',
            table='tblsituacaoacao',
        ),
        migrations.AlterModelTable(
            name='vigenciapngi',
            table='tblvigenciapngi',
        ),
    ]
