# Generated by Django 6.0.1 on 2026-01-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes_pngi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='situacaoacao',
            table='acoes_pngi.tblsituacaoacao',
        ),
        migrations.AlterModelTable(
            name='vigenciapngi',
            table='acoes_pngi.tblvigenciapngi',
        ),
    ]
