# Generated by Django 6.0.1 on 2026-02-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes_pngi', '0002_add_new_tables'),
    ]

    operations = [
    ]
