# Generated by Django A.I. Assistant - Matriz PNGI FINAL
from django.db import migrations


def create_pngi_matrix_permissions(apps, schema_editor):
    """
    IMPLEMENTA MATRIZ PNGI CORRETA:
    GESTOR_PNGI: Total + gerencia users/roles
    COORDENADOR_PNGI: N2 + operações (sem N1)
    OPERADOR_ACAO: operações apenas (sem configs)
    CONSULTOR_PNGI: read apenas
    """
    from django.contrib.auth.models import Group, Permission
    from django.contrib.contenttypes.models import ContentType

    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")

    # 1. Limpar groups PNGI existentes
    pngi_groups = ["GESTOR_PNGI", "COORDENADOR_PNGI", "OPERADOR_ACAO", "CONSULTOR_PNGI"]
    Group.objects.filter(name__in=pngi_groups).delete()

    # 2. Modelos da matriz (nomes EXATOS)
    models = {
        # NÍVEL 1 - GESTOR APENAS
        "situacaoacao": None,
        "tipoentravealerta": None,
        # NÍVEL 2 - GESTOR + COORD
        "eixo": None,
        "vigenciapngi": None,
        "tipoanotacaoalinhamento": None,
        # OPERAÇÕES - GESTOR + COORD + OPERADOR
        "acoes": None,
        "acaoprazo": None,
        "acaodestaque": None,
        "acaoanotacaoalinhamento": None,
        "usuarioresponsavel": None,
        "relacaoacaousuarioresponsavel": None,
    }

    # Mapear ContentTypes reais
    for model_name in models:
        try:
            ct = ContentType.objects.get(app_label="acoes_pngi", model=model_name)
            models[model_name] = ct
            print(f"✅ {model_name}")
        except ContentType.DoesNotExist:
            print(f"⚠️  {model_name}")

    all_models = list(models.keys())

    # Helpers
    def add_model_perms(group, model_names, read=True, write=False):
        for model_name in model_names:
            ct = models.get(model_name)
            if ct:
                if read:
                    try:
                        group.permissions.add(
                            Permission.objects.get(
                                codename=f"view_{model_name}", content_type=ct
                            )
                        )
                    except Permission.DoesNotExist:
                        pass
                if write:
                    for action in ["add", "change", "delete"]:
                        try:
                            group.permissions.add(
                                Permission.objects.get(
                                    codename=f"{action}_{model_name}", content_type=ct
                                )
                            )
                        except Permission.DoesNotExist:
                            pass

    def add_auth_perms(group, codenames):
        for codename in codenames:
            try:
                group.permissions.add(Permission.objects.get(codename=codename))
            except Permission.DoesNotExist:
                pass

    # GESTOR_PNGI: TOTAL
    gestor = Group.objects.create(name="GESTOR_PNGI")
    add_model_perms(gestor, all_models, read=True, write=True)
    add_auth_perms(
        gestor,
        [
            "add_user",
            "change_user",
            "delete_user",
            "view_user",
            "add_group",
            "change_group",
            "delete_group",
            "view_group",
        ],
    )

    # COORDENADOR_PNGI: read ALL + N2 + OPERAÇÕES
    coord = Group.objects.create(name="COORDENADOR_PNGI")
    add_model_perms(coord, all_models, read=True, write=False)
    n2_models = ["eixo", "vigenciapngi", "tipoanotacaoalinhamento"]
    ops_models = [
        "acoes",
        "acaoprazo",
        "acaodestaque",
        "acaoanotacaoalinhamento",
        "usuarioresponsavel",
        "relacaoacaousuarioresponsavel",
    ]
    add_model_perms(coord, n2_models + ops_models, read=False, write=True)
    add_auth_perms(coord, ["view_user", "view_group"])

    # OPERADOR_ACAO: read ALL + OPERAÇÕES
    operador = Group.objects.create(name="OPERADOR_ACAO")
    add_model_perms(operador, all_models, read=True, write=False)
    add_model_perms(operador, ops_models, read=False, write=True)
    add_auth_perms(operador, ["view_user", "view_group"])

    # CONSULTOR_PNGI: read ALL
    consultor = Group.objects.create(name="CONSULTOR_PNGI")
    add_model_perms(consultor, all_models, read=True, write=False)
    add_auth_perms(consultor, ["view_user", "view_group"])

    print("🎉 MATRIZ PNGI 100% IMPLEMENTADA!")
    print("✅ GESTOR(total), COORD(N2+ops), OPERADOR(ops), CONSULTOR(read)")


def reverse_pngi_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    pngi_groups = ["GESTOR_PNGI", "COORDENADOR_PNGI", "OPERADOR_ACAO", "CONSULTOR_PNGI"]
    Group.objects.filter(name__in=pngi_groups).delete()


class Migration(migrations.Migration):
    """
    MIGRAÇÃO FINAL - MATRIZ DE PERMISSÕES PNGI
    Executa após todos ContentTypes e dados domain existirem
    """

    dependencies = [
        ("acoes_pngi", "0002_load_config_data"),
        ("accounts", "0002_load_domain_data"),
        ("auth", "__latest__"),
        ("contenttypes", "__latest__"),
    ]

    operations = [
        migrations.RunPython(
            create_pngi_matrix_permissions, reverse_code=reverse_pngi_permissions
        ),
    ]
