# Generated by Django 6.0.1 on 2026-03-06 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes_pngi', '0003_create_pngi_permissions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='acaoanotacaoalinhamento',
            table='tblacaoanotacaoalinhamento',
        ),
        migrations.AlterModelTable(
            name='acaodestaque',
            table='tblacaodestaque',
        ),
        migrations.AlterModelTable(
            name='acaoprazo',
            table='tblacaoprazo',
        ),
        migrations.AlterModelTable(
            name='acoes',
            table='tblacoes',
        ),
        migrations.AlterModelTable(
            name='eixo',
            table='tbleixos',
        ),
        migrations.AlterModelTable(
            name='relacaoacaousuarioresponsavel',
            table='tblrelacaoacaousuarioresponsavel',
        ),
        migrations.AlterModelTable(
            name='situacaoacao',
            table='tblsituacaoacao',
        ),
        migrations.AlterModelTable(
            name='tipoanotacaoalinhamento',
            table='tbltipoanotacaoalinhamento',
        ),
        migrations.AlterModelTable(
            name='tipoentravealerta',
            table='tbltipoentravealerta',
        ),
        migrations.AlterModelTable(
            name='usuarioresponsavel',
            table='tblusuarioresponsavel',
        ),
        migrations.AlterModelTable(
            name='vigenciapngi',
            table='tblvigenciapngi',
        ),
    ]
