# Generated by Django 6.0.1 on 2026-02-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes_pngi', '0003_sync_situacaoacao_timestamps'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='eixo',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='situacaoacao',
            table_comment=None,
        ),
        migrations.AlterModelTableComment(
            name='vigenciapngi',
            table_comment=None,
        ),
        migrations.AddField(
            model_name='situacaoacao',
            name='created_at',
            field=models.DateTimeField(blank=True, db_column='created_at', null=True),
        ),
        migrations.AddField(
            model_name='situacaoacao',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_column='updated_at', null=True),
        ),
    ]
