# Generated by Django 6.0.1 on 2026-02-10 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes_pngi', '0004_alter_eixo_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacaoacao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='created_at', default=datetime.datetime(2026, 2, 10, 14, 40, 51, 359386, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='situacaoacao',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', default=datetime.datetime(2026, 2, 10, 14, 41, 39, 501294, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
