# Generated by Django 6.0.1 on 2026-02-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes_pngi', '0005_alter_situacaoacao_created_at_and_more')
    ]

    operations = [
        migrations.AddField(
            model_name='acoes',
            name='ideixo',
            field=models.ForeignKey(db_column='ideixo', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='acoes_pngi.eixo'),
        ),
    ]
