# Generated by Django 6.0.1 on 2026-02-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes_pngi', '0007_acoes_ideixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acoes',
            name='idsituacaoacao',
            field=models.ForeignKey(blank=True, db_column='idsituacaoacao', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='acoes_pngi.situacaoacao'),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='ideixo',
            field=models.ForeignKey(blank=True, db_column='ideixo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acoes', to='acoes_pngi.eixo'),
        ),
    ]
